/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserRegisterRouteImport } from './routes/user/register'
import { Route as UserPaymentsRouteImport } from './routes/user/payments'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRiskRouteImport } from './routes/admin/risk'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOddsRouteImport } from './routes/admin/odds'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBetsRouteImport } from './routes/admin/bets'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserPaymentsRoute = UserPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOddsRoute = AdminOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBetsRoute = AdminBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/admin/bets': typeof AdminBetsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/admin/bets': typeof AdminBetsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/admin/bets': typeof AdminBetsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/odds': typeof AdminOddsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/user'
    | '/admin/bets'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/odds'
    | '/admin/reports'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/login'
    | '/user/payments'
    | '/user/register'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/bets'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/odds'
    | '/admin/reports'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/login'
    | '/user/payments'
    | '/user/register'
    | '/admin'
    | '/user'
  id:
    | '__root__'
    | '/admin'
    | '/user'
    | '/admin/bets'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/odds'
    | '/admin/reports'
    | '/admin/risk'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/login'
    | '/user/payments'
    | '/user/register'
    | '/admin/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/user/register': {
      id: '/user/register'
      path: '/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/payments': {
      id: '/user/payments'
      path: '/payments'
      fullPath: '/user/payments'
      preLoaderRoute: typeof UserPaymentsRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/login': {
      id: '/user/login'
      path: '/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/odds': {
      id: '/admin/odds'
      path: '/odds'
      fullPath: '/admin/odds'
      preLoaderRoute: typeof AdminOddsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bets': {
      id: '/admin/bets'
      path: '/bets'
      fullPath: '/admin/bets'
      preLoaderRoute: typeof AdminBetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBetsRoute: typeof AdminBetsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminOddsRoute: typeof AdminOddsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBetsRoute: AdminBetsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminOddsRoute: AdminOddsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserLoginRoute: typeof UserLoginRoute
  UserPaymentsRoute: typeof UserPaymentsRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserLoginRoute: UserLoginRoute,
  UserPaymentsRoute: UserPaymentsRoute,
  UserRegisterRoute: UserRegisterRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
