/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserRegisterRouteImport } from './routes/user/register'
import { Route as UserPaymentsRouteImport } from './routes/user/payments'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as User_layoutRouteImport } from './routes/user/__layout'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'

const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPaymentsRoute = UserPaymentsRouteImport.update({
  id: '/user/payments',
  path: '/user/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const User_layoutRoute = User_layoutRouteImport.update({
  id: '/user/__layout',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof Admin_layoutRoute
  '/user': typeof User_layoutRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/__layout': typeof Admin_layoutRoute
  '/user/__layout': typeof User_layoutRoute
  '/user/login': typeof UserLoginRoute
  '/user/payments': typeof UserPaymentsRoute
  '/user/register': typeof UserRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/user'
    | '/user/login'
    | '/user/payments'
    | '/user/register'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/user' | '/user/login' | '/user/payments' | '/user/register'
  id:
    | '__root__'
    | '/admin/__layout'
    | '/user/__layout'
    | '/user/login'
    | '/user/payments'
    | '/user/register'
    | '/admin/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  User_layoutRoute: typeof User_layoutRoute
  UserLoginRoute: typeof UserLoginRoute
  UserPaymentsRoute: typeof UserPaymentsRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/payments': {
      id: '/user/payments'
      path: '/user/payments'
      fullPath: '/user/payments'
      preLoaderRoute: typeof UserPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/__layout': {
      id: '/user/__layout'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof User_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  User_layoutRoute: User_layoutRoute,
  UserLoginRoute: UserLoginRoute,
  UserPaymentsRoute: UserPaymentsRoute,
  UserRegisterRoute: UserRegisterRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
