ALTER TABLE "admin_settings"
ADD COLUMN "platform_name" TEXT NOT NULL DEFAULT 'BetWise',
ADD COLUMN "environment" TEXT NOT NULL DEFAULT 'sandbox',
ADD COLUMN "default_currency" TEXT NOT NULL DEFAULT 'KES',
ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'Africa/Nairobi',
ADD COLUMN "maintenance_mode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "registration_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "default_wallet_balance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "min_deposit" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "max_deposit" INTEGER NOT NULL DEFAULT 200000,
ADD COLUMN "min_withdrawal" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "max_withdrawal" INTEGER NOT NULL DEFAULT 100000,
ADD COLUMN "daily_transaction_limit" INTEGER NOT NULL DEFAULT 500000,
ADD COLUMN "max_active_bets_per_user" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN "default_user_role" TEXT NOT NULL DEFAULT 'USER',
ADD COLUMN "auto_verification_rule" TEXT NOT NULL DEFAULT 'email',
ADD COLUMN "kyc_required" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "kyc_require_id" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "kyc_require_phone" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "kyc_require_email" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "withdrawal_requires_kyc" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "minimum_age" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN "allowed_countries" TEXT[] NOT NULL DEFAULT ARRAY['KE']::TEXT[],
ADD COLUMN "payment_mpesa_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "payment_bank_transfer_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "payment_airtel_money_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "payment_card_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mpesa_shortcode" TEXT NOT NULL DEFAULT '174379',
ADD COLUMN "mpesa_consumer_key" TEXT NOT NULL DEFAULT 'replace-with-consumer-key',
ADD COLUMN "mpesa_consumer_secret" TEXT NOT NULL DEFAULT 'replace-with-consumer-secret',
ADD COLUMN "mpesa_passkey" TEXT NOT NULL DEFAULT 'replace-with-passkey',
ADD COLUMN "mpesa_callback_url" TEXT NOT NULL DEFAULT '',
ADD COLUMN "mpesa_transaction_fee_percent" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "mpesa_auto_withdraw_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mpesa_withdrawal_approval_threshold" INTEGER NOT NULL DEFAULT 50000,
ADD COLUMN "min_bet_amount" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "max_bet_amount" INTEGER NOT NULL DEFAULT 200000,
ADD COLUMN "max_win_per_bet" INTEGER NOT NULL DEFAULT 1000000,
ADD COLUMN "odds_margin_percent" DOUBLE PRECISION NOT NULL DEFAULT 7,
ADD COLUMN "bet_delay_ms" INTEGER NOT NULL DEFAULT 1500,
ADD COLUMN "cashout_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "cashout_margin_percent" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "allow_live_betting" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "max_exposure_per_event" INTEGER NOT NULL DEFAULT 2000000,
ADD COLUMN "max_exposure_per_market" INTEGER NOT NULL DEFAULT 800000,
ADD COLUMN "max_payout_per_day" INTEGER NOT NULL DEFAULT 8000000,
ADD COLUMN "high_risk_bet_threshold" INTEGER NOT NULL DEFAULT 250000,
ADD COLUMN "auto_block_suspicious_users" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "welcome_bonus_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "bonus_mode" TEXT NOT NULL DEFAULT 'percentage',
ADD COLUMN "bonus_amount" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN "bonus_percent" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN "wagering_requirement_multiplier" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN "bonus_expiry_hours" INTEGER NOT NULL DEFAULT 168,
ADD COLUMN "max_bonus_per_user" INTEGER NOT NULL DEFAULT 3000,
ADD COLUMN "cashback_rule" TEXT NOT NULL DEFAULT '5% cashback for net losses above KES 2,000, credited weekly.',
ADD COLUMN "sms_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "email_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notify_deposit_success" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notify_withdrawal_success" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notify_bet_placed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "notify_bet_result" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "notify_admin_alerts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sports_api_key" TEXT NOT NULL DEFAULT 'replace-with-sports-api-key',
ADD COLUMN "odds_provider_name" TEXT NOT NULL DEFAULT 'TheOddsAPI',
ADD COLUMN "primary_webhook_url" TEXT NOT NULL DEFAULT 'https://example.com/webhooks/sports',
ADD COLUMN "fallback_webhook_url" TEXT NOT NULL DEFAULT 'https://example.com/webhooks/sports/fallback',
ADD COLUMN "retry_attempts" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN "retry_backoff_ms" INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN "requests_per_minute" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN "admin_two_factor_required" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "password_min_length" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN "require_uppercase" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "require_number" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "require_special_char" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "session_timeout_minutes" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN "max_login_attempts" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "ip_whitelist" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "ip_blacklist" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "winnings_tax_percent" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN "deposit_tax_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "commission_percent" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN "rounding_rule" TEXT NOT NULL DEFAULT 'nearest_1',
ADD COLUMN "affiliate_commission_percent" DOUBLE PRECISION NOT NULL DEFAULT 5,
ADD COLUMN "multi_level_referrals_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "affiliate_minimum_payout_threshold" INTEGER NOT NULL DEFAULT 1500,
ADD COLUMN "affiliate_withdrawal_rule" TEXT NOT NULL DEFAULT 'Monthly payouts after reconciliation and KYC check.',
ADD COLUMN "terms_and_conditions" TEXT NOT NULL DEFAULT 'By using this platform, you agree to our betting terms, fair usage policies, and anti-fraud controls.',
ADD COLUMN "privacy_policy" TEXT NOT NULL DEFAULT 'We process account and transactional data strictly for service operations, regulatory compliance, and fraud prevention.',
ADD COLUMN "responsible_gambling_message" TEXT NOT NULL DEFAULT 'Bet responsibly. Set limits and seek support if betting affects your wellbeing.',
ADD COLUMN "support_contact_info" TEXT NOT NULL DEFAULT 'support@betwise.co.ke | +254700000000';

ALTER TABLE "admin_settings" DROP COLUMN IF EXISTS "config";
