import { Router } from "express";
import { betsAdminRouter } from "./admin/bets";
import { eventsAdminRouter } from "./admin/events";
import { oddsAdminRouter } from "./admin/odds";
import { sportCategoriesCompatRouter } from "./admin/sport-categories-compat";
import { adminCustomEventsRouter } from "./admin/custom-events";
import { sportCategoriesRouter } from "./admin/sport-categories";
import { authRouter } from "./auth.routes";
import { adminRouter } from "./admin";
import { healthRouter } from "./health";
import { myBetsRouter } from "./my-bets";
import { notificationRouter } from "./notifications";
import { paymentRouter } from "./payments";
import { paystackRouter } from "./paystack";
import { profileRouter } from "./profile";
import { liveRouter } from "./live";
import { userBetsRouter } from "./user/bets";
import { userEventsRouter } from "./user/events";
import { userCustomEventsRouter } from "./user/custom-events";
import { contactRouter } from "./contact";
import { newsletterRouter } from "./newsletter";
import { appealsRouter } from "./appeals";

const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(authRouter);
apiRouter.use(adminRouter);
apiRouter.use(paymentRouter);
apiRouter.use("/payments/paystack", paystackRouter);
apiRouter.use(profileRouter);
apiRouter.use(notificationRouter);
apiRouter.use(myBetsRouter);
apiRouter.use(liveRouter);
apiRouter.use(eventsAdminRouter);
apiRouter.use(betsAdminRouter);
apiRouter.use(oddsAdminRouter);
apiRouter.use(sportCategoriesCompatRouter);
apiRouter.use(adminCustomEventsRouter);
apiRouter.use(sportCategoriesRouter);
apiRouter.use(userEventsRouter);
apiRouter.use(userBetsRouter);
apiRouter.use(userCustomEventsRouter);
apiRouter.use(contactRouter);
apiRouter.use(newsletterRouter);
apiRouter.use(appealsRouter);

export { apiRouter };
